//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnstrumanSatis_MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketDetail
    {
        public int ID { get; set; }
        public Nullable<int> BasketID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Product Product { get; set; }
    }
}
